"""`agentmesh init`: analyze -> (ask) -> generate. Re-runnable without clobbering human edits."""
from __future__ import annotations

import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

from . import bootstrap, discovery, fsutil, gitutil
from .config import (DEFAULT_QUALITY_ORDER, DEFAULTS, MACHINE_KEYS, SCHEMA_VERSION, ProjectPaths, deep_merge,
                     dump_yaml, load_yaml)
from .errors import ProjectError
from .project_analyzer import ProjectProfile, analyze, apply_answers
from .reference import build_index, resolve_reference
from .registry import Registry
from .roles import render_role, role_policy, select_roles
from .workflow import generate_workflow

Asker = Callable[[str, list[str], str], str]
PROJECT_HEADER = ("# AgentMesh project config.\n# Machine-owned (regenerated by `agentmesh init`): schema, project, detected, roles, verification.\n"
                  "# Human-owned (preserved): manager, routing, fallback, delegation, workers, worktree, references, overrides.\n")


@dataclass
class InitReport:
    profile: ProjectProfile
    roles: list[str]
    manager: str
    actions: dict[str, str] = field(default_factory=dict)
    stale_roles: list[str] = field(default_factory=list)
    asked: dict[str, str] = field(default_factory=dict)
    assumptions: list[str] = field(default_factory=list)
    ready_workers: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


def tty_asker(text: str, choices: list[str], default: str) -> str:
    print(f"\n? {text}")
    for i, c in enumerate(choices, 1):
        print(f"   {i}) {c}{'  (default)' if c == default else ''}")
    raw = input("  > ").strip()
    if not raw:
        return default
    if raw.isdigit() and 1 <= int(raw) <= len(choices):
        return choices[int(raw) - 1]
    return raw if raw in choices else default


def _pick_manager(requested: str | None, existing: str | None, ready: list[str], registry: Registry) -> str:
    if requested:
        return registry.resolve(requested)
    if existing:
        return existing
    if os.environ.get("CLAUDECODE") and "claude" in ready:
        return "claude"
    for name in DEFAULT_QUALITY_ORDER:
        if name in ready:
            return name
    return "claude"


def _detected_block(p: ProjectProfile) -> dict:
    return {
        "components": [{"path": c.path, "type": c.type, "stack": c.stack, "frameworks": c.frameworks,
                        "details": c.details, "inferred": c.inferred} for c in p.components],
        "workspace_markers": p.workspace_markers, "docs": p.docs, "ci": p.ci, "test_dirs": p.test_dirs,
        "contracts": p.contracts, "migrations": p.migrations, "localization": p.localization,
        "sensitive": p.sensitive, "instruction_files": p.instruction_files,
    }


def init_project(root: Path, registry: Registry, *, asker: Asker | None = None, answers: dict[str, str] | None = None,
                 manager: str | None = None, reference: str | None = None, dry_run: bool = False,
                 security: bool | None = None, refresh: bool = True, path_env: str | None = None,
                 report_line: Callable[[str], None] = lambda s: None) -> InitReport:
    root = root.resolve()
    if not root.is_dir():
        raise ProjectError(f"not a directory: {root}")
    git_root = gitutil.repo_root(root)
    if git_root and git_root != root:
        report_line(f"note: {root} is inside git repo {git_root}; initializing here (use that path to cover the whole repo)")
    paths = ProjectPaths(root)
    profile = analyze(root)

    given = dict(answers or {})
    asked: dict[str, str] = {}
    for q in profile.questions:
        if q.id in given:
            asked[q.id] = given[q.id]
        elif asker is not None:
            asked[q.id] = asker(q.text, q.choices, q.default)
        else:
            asked[q.id] = q.default
            profile.assumptions.append(f"assumed {q.id}={q.default} (not interactive): {q.text}")
    apply_answers(profile, asked)
    if security is not None:
        profile.security_review = security

    existing = load_yaml(paths.project_yaml) if paths.project_yaml.is_file() else {}
    rep = discovery.current(registry, refresh=refresh, path_env=path_env)
    ready = [a.name for a in rep.agents if a.ready]
    mgr = _pick_manager(manager, (existing.get("manager") or {}).get("default"), ready, registry)
    roles = select_roles(profile)
    out = InitReport(profile, roles, mgr, asked=asked, assumptions=profile.assumptions, ready_workers=ready)
    act = out.actions

    # ---- reference
    refs = list(existing.get("references") or [])
    ref_notes: str | None = None
    if reference:
        ref_root = resolve_reference(reference, paths)
        if reference not in refs:
            refs.append(reference)
        if not dry_run:
            paths.references_dir.mkdir(parents=True, exist_ok=True)
        sections = [build_index(resolve_reference(r, paths), r) for r in refs]
        act[".agentmesh/references/index.md"] = fsutil.write_generated(
            paths.references_dir / "index.md", "# Reference index\n\n" + "\n".join(sections), "md", dry_run)
    if refs or (paths.references_dir / "index.md").exists():
        ref_notes = "`.agentmesh/references/index.md` (methodology reference; project-specific rules in it do not apply)"

    # ---- role files
    for role in roles:
        act[f".agentmesh/agents/{role}.md"] = fsutil.write_generated(
            paths.agents_dir / f"{role}.md", render_role(role, profile, ref_notes), "md", dry_run)
    if paths.agents_dir.is_dir():
        for f in sorted(paths.agents_dir.glob("*.md")):
            if f.stem not in roles and fsutil.split_stamp(f.read_text(encoding="utf-8"))[0]:
                out.stale_roles.append(f.stem)

    # ---- workflow
    wf = generate_workflow(profile.name, profile.kind, roles)
    act[".agentmesh/workflow.yaml"] = fsutil.write_generated(paths.workflow_yaml, dump_yaml(wf), "yaml", dry_run)

    # ---- project.yaml (machine keys regenerated, human keys preserved)
    human = {k: v for k, v in existing.items() if k not in MACHINE_KEYS}
    defaults = deep_merge(DEFAULTS, {"routing": {"preferred_order": [n for n in DEFAULT_QUALITY_ORDER if n in ready]}})
    if "preferred_order" in (human.get("routing") or {}):
        defaults["routing"].pop("preferred_order")
    human = deep_merge(defaults, human)
    human["manager"]["default"] = mgr
    extra = bootstrap.MANAGER_FILES.get(mgr)
    if extra and extra not in human["manager"]["bootstrap_files"]:
        human["manager"]["bootstrap_files"] = [*human["manager"]["bootstrap_files"], extra]
    human["references"] = refs
    commands = [{"component": c.path, **v} for c in profile.components for v in c.verification]
    data = {
        "schema": SCHEMA_VERSION,
        "project": {"name": profile.name, "kind": profile.kind, "git": profile.is_git,
                    "assumptions": profile.assumptions, "answers": asked},
        "detected": _detected_block(profile),
        "roles": {r: role_policy(r, profile) for r in roles},
        "verification": {"commands": commands},
        **human,
    }
    new_text = PROJECT_HEADER + dump_yaml(data)
    if not paths.project_yaml.exists():
        act[".agentmesh/project.yaml"] = "created"
    elif load_yaml(paths.project_yaml) == load_yaml_text(new_text):
        act[".agentmesh/project.yaml"] = "unchanged"
    else:
        act[".agentmesh/project.yaml"] = "updated"
    if not dry_run and act[".agentmesh/project.yaml"] != "unchanged":
        paths.mesh.mkdir(parents=True, exist_ok=True)
        paths.project_yaml.write_text(new_text, encoding="utf-8")

    # ---- housekeeping dirs, readme, ignore, manager bootstrap
    if not dry_run:
        for d in (paths.tasks_dir, paths.reports_dir, paths.references_dir):
            d.mkdir(parents=True, exist_ok=True)
            (d / ".gitkeep").touch()
        paths.runtime_dir.mkdir(parents=True, exist_ok=True)
    act[".agentmesh/README.md"] = fsutil.write_generated(paths.mesh / "README.md", bootstrap.project_readme(), "md", dry_run)
    act[".gitignore"] = bootstrap.update_gitignore(root, dry_run)
    section = bootstrap.manager_section(profile.name, profile.kind, roles, int(human["delegation"]["max_depth"]),
                                        int(wf["limits"]["max_correction_rounds"]))
    for f, status in bootstrap.write_manager_files(root, human["manager"]["bootstrap_files"], section, dry_run).items():
        act[f] = status
    if not ready:
        out.warnings.append("no READY worker CLI found: delegation will fail until one is installed (see `agentmesh discover`)")
    elif len(ready) == 1:
        out.warnings.append(f"only one READY worker ({ready[0]}): fallback has nowhere to go")
    if not profile.is_git:
        out.warnings.append("not a git repository: worktree isolation and diff/verify need git (run `git init` and commit)")
    elif not gitutil.has_commits(root):
        out.warnings.append("repository has no commits yet: worktrees need at least one commit")
    return out


def load_yaml_text(text: str) -> dict:
    import yaml
    return yaml.safe_load(text) or {}
